# Generated by Django 6.0.5 on 2026-05-19 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
