# Generated by Django 6.0.5 on 2026-05-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
    ]
