# Generated by Django 6.0.5 on 2026-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('No GST', 'No GST'), ('IGST', 'IGST')], default='GST', max_length=20),
        ),
    ]
