# Generated by Django 6.0.5 on 2026-06-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_invoice_igst_amount_invoice_igst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gtin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
