# Generated by Django 6.0.5 on 2026-05-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Main tab name', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji or Svg', max_length=50, null=True)),
                ('path', models.CharField(blank=True, help_text='Route if it has no children', max_length=200, null=True)),
                ('badge', models.IntegerField(blank=True, help_text='Optional number badge', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of Module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sub-tab name', max_length=100)),
                ('path', models.CharField(help_text='Route', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order of Child')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xeflow.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
