# Generated by Django 6.0.5 on 2026-05-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xeflow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
